var app = new Vue({
    el: '#app',
    data:{
        columns:[
            {
                title:'姓名',
                key:'name'
            },
            {
                title:'年龄',
                key:'age',
                sortable:true
            },
            {
                title:'出生日期',
                key:'birthday',
                sortable:true
            },
            {
                title:'地址',
                key:'address'
            }
        ],
        data:[
            {
                name:'letme',
                age:18,
                birthday:'1999-02-21',
                address:'武汉市江汉区'
            },
            {
                name:'mlxg',
                age:19,
                birthday:'1996-02-21',
                address:'武汉市江汉区'
            },
            {
                name:'xiaohu',
                age:20,
                birthday:'1989-02-21',
                address:'武汉市江汉区'
            },
            {
                name:'uzi',
                age:21,
                birthday:'1994-02-21',
                address:'武汉市江汉区'
            },
            {
                name:'ming',
                age:22,
                birthday:'1991-02-21',
                address:'武汉市江汉区'
            }
        ]
    },
    methods:{
        handleAddData:function(){
            this.data.push({
                name:'karsa',
                age:25,
                birthday:'1998-05-30',
                address:'武汉市洪山区'
            });
        }
    }
});